### ISSUE TITLE
Using published package on pypi doesn't work because readme is not found

### ISSUE THREAD

**Issue by maxnoe** [HDembinski/monolens#4]
```
❯ monolens
Traceback (most recent call last):
  File "/home/maxnoe/.local/bin/monolens", line 8, in <module>
    sys.exit(main())
  File "/home/maxnoe/.local/lib/python3.9/site-packages/monolens/__init__.py", line 25, in main
    intro = Intro()
  File "/home/maxnoe/.local/lib/python3.9/site-packages/monolens/intro.py", line 17, in __init__
    with open(Path(__file__).parent / ".." / "README.md") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/maxnoe/.local/lib/python3.9/site-packages/monolens/../README.md'
```

**Comment by HDembinski** [comment]
ist hoffentlich gerade gefixt
